/**
 * @file netlistSpice.ts
 * @description Generates SPICE (.cir) and Cadence Spectre native netlists from
 * DigiSim schematic nodes and edges. Maps component terminals to electrical nets,
 * formats 4-terminal MOSFETs, passive RLC components, voltage sources, diodes/LEDs,
 * and logic subcircuits with standard model cards and simulation controls.
 */

import type { DigiEdge, DigiNode, NetlistSpiceOptions } from '../../types';
import { terminalsOfNode } from './mna';

/**
 * Maps terminal keys across nodes and edges into distinct electrical net names.
 * Reference / ground terminals are mapped to net '0'.
 *
 * @param nodes - Canvas node list
 * @param edges - Canvas edge list
 * @returns Map from terminal key (`${nodeId}/${terminal}`) to net name (`N001`, `0`, etc.)
 */

/** Map node terminal keys to electrical net identifiers. */
export function buildNetMap(
  nodes: DigiNode[],
  edges: DigiEdge[]
): Map<string, string> {
  const parent = new Map<string, string>();
  for (const node of nodes) {
    for (const terminal of terminalsOfNode(node)) {
      const key = `${node.id}/${terminal}`;
      parent.set(key, key);
    }
  }

  const find = (key: string): string => {
    let root = key;
    while (parent.get(root) !== root) root = parent.get(root)!;
    let cursor = key;
    while (parent.get(cursor) !== root) {
      const next = parent.get(cursor)!;
      parent.set(cursor, root);
      cursor = next;
    }
    return root;
  };

  const union = (a: string, b: string): void => {
    if (parent.has(a) && parent.has(b)) parent.set(find(a), find(b));
  };

  const handleTerminal = (
    handle: string | null | undefined,
    nodeId: string,
    nodesById: Map<string, DigiNode>
  ): string => {
    if (handle && (handle.startsWith('t:') || handle.startsWith('s:'))) {
      return handle.slice(2);
    }
    if (handle) return handle;
    const node = nodesById.get(nodeId);
    return node ? terminalsOfNode(node)[0] : 'a';
  };

  const nodesById = new Map(nodes.map((n) => [n.id, n]));
  for (const edge of edges) {
    const srcTerm = handleTerminal(edge.sourceHandle, edge.source, nodesById);
    const tgtTerm = handleTerminal(edge.targetHandle, edge.target, nodesById);
    union(`${edge.source}/${srcTerm}`, `${edge.target}/${tgtTerm}`);
  }

  // Connect ground nodes and board GND pins to a common reference
  const gndKeys: string[] = [];
  for (const node of nodes) {
    if (node.type === 'ground') gndKeys.push(`${node.id}/gnd`);
    if (node.type === 'hardware') {
      for (const pin of node.data.pins ?? []) {
        if (pin.role === 'ground' || /^(gnd|ground)/i.test(pin.name)) {
          gndKeys.push(`${node.id}/${pin.name}`);
        }
      }
    }
  }
  for (let i = 1; i < gndKeys.length; i++) {
    union(gndKeys[0], gndKeys[i]);
  }

  const rootToNetName = new Map<string, string>();
  let netIndex = 1;
  const refRoot = gndKeys.length > 0 ? find(gndKeys[0]) : null;

  const result = new Map<string, string>();
  for (const key of Array.from(parent.keys())) {
    const root = find(key);
    if (refRoot && root === refRoot) {
      result.set(key, '0');
    } else {
      if (!rootToNetName.has(root)) {
        const name = `N${String(netIndex).padStart(3, '0')}`;
        rootToNetName.set(root, name);
        netIndex++;
      }
      result.set(key, rootToNetName.get(root)!);
    }
  }

  return result;
}

/**
 * Emit a standard SPICE (.cir) netlist representation of the circuit.
 *
 * @param nodes - Array of schematic nodes
 * @param edges - Array of schematic edges
 * @param options - Netlist generation parameters (title, format, etc.)
 * @returns Multi-line SPICE .cir string
 */
export function generateSpiceNetlist(
  nodes: DigiNode[],
  edges: DigiEdge[],
  options: NetlistSpiceOptions = {}
): string {
  const title = options.title ?? 'DigiSim Circuit SPICE Netlist';
  const netMap = buildNetMap(nodes, edges);
  const getNet = (nodeId: string, terminal: string): string =>
    netMap.get(`${nodeId}/${terminal}`) ?? '0';

  const lines: string[] = [];
  lines.push(`* ${title}`);
  lines.push('* Generated by DigiSim AI EDA Platform');
  lines.push('');

  if (options.includeModels !== false) {
    lines.push('* --- PDK Model Cards ---');
    lines.push('.model NMOS180 NMOS (LEVEL=1 VTO=0.45 TOX=4.0n KP=170u GAMMA=0.45 LAMBDA=0.04)');
    lines.push('.model PMOS180 PMOS (LEVEL=1 VTO=-0.42 TOX=4.0n KP=85u GAMMA=0.45 LAMBDA=0.04)');
    lines.push('.model DLED D (IS=1e-14 N=1.8 RS=8.0 BV=5.0 IBV=10u)');
    lines.push('.model SMOD VSWITCH (RON=0.01 ROFF=1e8 VON=2.5 VOFF=0.5)');
    lines.push('');
    lines.push('* --- Standard Logic Subcircuits ---');
    lines.push('.subckt AND2 IN1 IN2 OUT VDD VSS');
    lines.push('M1 INT1 IN1 VSS VSS NMOS180 W=1.8u L=0.18u');
    lines.push('M2 OUT IN2 INT1 VSS NMOS180 W=1.8u L=0.18u');
    lines.push('M3 OUT IN1 VDD VDD PMOS180 W=3.6u L=0.18u');
    lines.push('M4 OUT IN2 VDD VDD PMOS180 W=3.6u L=0.18u');
    lines.push('.ends AND2');
    lines.push('');
    lines.push('.subckt INV IN OUT VDD VSS');
    lines.push('M1 OUT IN VSS VSS NMOS180 W=1.8u L=0.18u');
    lines.push('M2 OUT IN VDD VDD PMOS180 W=3.6u L=0.18u');
    lines.push('.ends INV');
    lines.push('');
  }

  lines.push('* --- Component Instances ---');
  let resCount = 1;
  let vCount = 1;
  let ledCount = 1;
  let swCount = 1;
  let nmosCount = 1;
  let pmosCount = 1;
  let gateCount = 1;

  for (const node of nodes) {
    const type = node.type ?? '';
    const name = node.data.label.replace(/\s+/g, '_');

    if (type === 'resistor') {
      const nA = getNet(node.id, 'a');
      const nB = getNet(node.id, 'b');
      const ohms = node.data.param ?? 220;
      lines.push(`R${resCount++} ${nA} ${nB} ${ohms} ; ${name}`);
    } else if (type === 'potentiometer') {
      const nA = getNet(node.id, 'a');
      const nB = getNet(node.id, 'b');
      const nWip = `${nA}_WIP`;
      const maxOhms = node.data.param ?? 10000;
      const pct = (node.data.percent ?? 50) / 100;
      const r1 = Math.max(0.1, maxOhms * pct);
      const r2 = Math.max(0.1, maxOhms * (1 - pct));
      lines.push(`Rpot1_${resCount} ${nA} ${nWip} ${r1.toFixed(1)} ; ${name} upper`);
      lines.push(`Rpot2_${resCount++} ${nWip} ${nB} ${r2.toFixed(1)} ; ${name} lower`);
    } else if (type === 'vsource' || type === 'input') {
      const pos = getNet(node.id, 'pos');
      const neg = getNet(node.id, 'neg');
      const volts = node.data.param ?? (node.data.value === 1 ? 5 : 0);
      lines.push(`V${vCount++} ${pos} ${neg} DC ${volts} ; ${name}`);
    } else if (type === 'led' || type === 'output') {
      const anode = getNet(node.id, 'anode');
      const cathode = getNet(node.id, 'cathode');
      lines.push(`D${ledCount++} ${anode} ${cathode} DLED ; ${name}`);
    } else if (type === 'analogSwitch') {
      const nA = getNet(node.id, 'a');
      const nB = getNet(node.id, 'b');
      const ctrl = node.data.closed ? 'VDD' : '0';
      lines.push(`S${swCount++} ${nA} ${nB} ${ctrl} 0 SMOD ; ${name} (${node.data.closed ? 'closed' : 'open'})`);
    } else if (type === 'nmos' || type === 'nmosNode') {
      const d = getNet(node.id, 'd');
      const g = getNet(node.id, 'g');
      const s = getNet(node.id, 's');
      const b = getNet(node.id, 'b') !== '0' ? getNet(node.id, 'b') : s;
      const w = node.data.width ?? 1.8;
      const l = node.data.length ?? 0.18;
      lines.push(`M_NMOS${nmosCount++} ${d} ${g} ${s} ${b} NMOS180 W=${w}u L=${l}u ; ${name}`);
    } else if (type === 'pmos' || type === 'pmosNode') {
      const d = getNet(node.id, 'd');
      const g = getNet(node.id, 'g');
      const s = getNet(node.id, 's');
      const b = getNet(node.id, 'b') !== '0' ? getNet(node.id, 'b') : s;
      const w = node.data.width ?? 3.6;
      const l = node.data.length ?? 0.18;
      lines.push(`M_PMOS${pmosCount++} ${d} ${g} ${s} ${b} PMOS180 W=${w}u L=${l}u ; ${name}`);
    } else if (['andGate', 'orGate', 'nandGate', 'norGate', 'xorGate', 'xnorGate', 'notGate'].includes(type)) {
      const in1 = getNet(node.id, 'a');
      const in2 = type === 'notGate' ? '0' : getNet(node.id, 'b');
      const out = getNet(node.id, 'out');
      const subckt = type === 'notGate' ? 'INV' : 'AND2';
      lines.push(`X_GATE${gateCount++} ${in1} ${in2} ${out} VDD 0 ${subckt} ; ${name}`);
    }
  }

  lines.push('');
  lines.push('* --- Simulation Directives ---');
  lines.push('.op');
  lines.push('.end');

  return lines.join('\n');
}

/**
 * Emit a Cadence Spectre native syntax netlist representation of the circuit.
 *
 * @param nodes - Array of schematic nodes
 * @param edges - Array of schematic edges
 * @param options - Netlist options
 * @returns Multi-line Spectre native netlist string
 */
export function generateSpectreNetlist(
  nodes: DigiNode[],
  edges: DigiEdge[],
  options: NetlistSpiceOptions = {}
): string {
  const title = options.title ?? 'DigiSim Circuit Spectre Netlist';
  const netMap = buildNetMap(nodes, edges);
  const getNet = (nodeId: string, terminal: string): string =>
    netMap.get(`${nodeId}/${terminal}`) ?? '0';

  const lines: string[] = [];
  lines.push(`// ${title}`);
  lines.push('// Cadence Spectre Native Format — Generated by DigiSim');
  lines.push('simulator lang=spectre');
  lines.push('global 0');
  lines.push('');

  lines.push('// --- Model Cards ---');
  lines.push('model nmos180 nmos level=1 vto=0.45 tox=4.0n kp=170u lambda=0.04');
  lines.push('model pmos180 pmos level=1 vto=-0.42 tox=4.0n kp=85u lambda=0.04');
  lines.push('model dled diode is=1e-14 n=1.8 rs=8.0');
  lines.push('');

  lines.push('// --- Components ---');
  let idx = 1;
  for (const node of nodes) {
    const type = node.type ?? '';
    const name = node.data.label.toLowerCase().replace(/\s+/g, '_');

    if (type === 'resistor') {
      const nA = getNet(node.id, 'a');
      const nB = getNet(node.id, 'b');
      const ohms = node.data.param ?? 220;
      lines.push(`r${idx++} (${nA} ${nB}) resistor r=${ohms} // ${name}`);
    } else if (type === 'vsource' || type === 'input') {
      const pos = getNet(node.id, 'pos');
      const neg = getNet(node.id, 'neg');
      const volts = node.data.param ?? (node.data.value === 1 ? 5 : 0);
      lines.push(`v${idx++} (${pos} ${neg}) vsource dc=${volts} type=dc // ${name}`);
    } else if (type === 'nmos' || type === 'nmosNode') {
      const d = getNet(node.id, 'd');
      const g = getNet(node.id, 'g');
      const s = getNet(node.id, 's');
      const b = getNet(node.id, 'b') !== '0' ? getNet(node.id, 'b') : s;
      const w = node.data.width ?? 1.8;
      const l = node.data.length ?? 0.18;
      lines.push(`m${idx++} (${d} ${g} ${s} ${b}) nmos180 w=${w}u l=${l}u // ${name}`);
    } else if (type === 'pmos' || type === 'pmosNode') {
      const d = getNet(node.id, 'd');
      const g = getNet(node.id, 'g');
      const s = getNet(node.id, 's');
      const b = getNet(node.id, 'b') !== '0' ? getNet(node.id, 'b') : s;
      const w = node.data.width ?? 3.6;
      const l = node.data.length ?? 0.18;
      lines.push(`m${idx++} (${d} ${g} ${s} ${b}) pmos180 w=${w}u l=${l}u // ${name}`);
    }
  }

  lines.push('');
  lines.push('// --- Analyses ---');
  lines.push('dcOp dc dev=v1 param=dc start=0 stop=5 step=0.1');
  lines.push('');

  return lines.join('\n');
}
