/**
 * @file sampleCircuitsData.ts
 * @description Curated, 1-click playable example circuits for the DigiSim Showcase gallery.
 * Covers deep-submicron CMOS ICs (180nm/90nm/28nm), analog amplifiers, high-speed RF filters,
 * multi-bit digital logic, and pulse generators.
 */

import type { SampleCircuit } from '../../types';

export const SAMPLE_CIRCUITS: SampleCircuit[] = [
  {
    id: 'cmos-inverter-180nm',
    title: '180nm CMOS Inverter',
    subtitle: 'DC Transfer Curve (VTC) & Transient Rail-to-Rail Switching',
    description:
      'Complementary MOS inverter featuring standard 180nm PDK PMOS (W=2.4µm, L=0.18µm) and NMOS (W=1.2µm, L=0.18µm). Delivers a symmetrical switching threshold (V_M ≈ 0.9V), maximum noise margins, and sub-nanosecond propagation delay.',
    techNode: '180nm',
    category: 'cmos',
    difficulty: 'Beginner',
    badgeColor: '#6366f1',
    icon: '⚡',
    stats: {
      nodes: 6,
      edges: 6,
      speed: '1.2 GHz',
      power: '45 µW',
      gain: '-18.5 V/V',
    },
    features: [
      'Matched 2:1 Wp/Wn channel mobility symmetry',
      'BSIM3v3 CDF layout parasitic calculations',
      'Live Cutoff / Triode / Saturation region badges',
      'Automated DC transfer curve & transient analysis',
    ],
    nodes: [
      {
        id: 'inv-in',
        type: 'input',
        position: { x: 60, y: 190 },
        data: { label: 'VIN (0/1)', value: 0 },
      },
      {
        id: 'inv-vdd',
        type: 'vsource',
        position: { x: 260, y: 30 },
        data: { label: 'VDD (1.8V)', param: 1.8 },
      },
      {
        id: 'inv-pmos',
        type: 'pmos',
        position: { x: 250, y: 120 },
        data: {
          label: 'PMOS_P1',
          techNode: '180nm',
          width: 2.4,
          length: 0.18,
          nf: 1,
          autoBulk: true,
        },
      },
      {
        id: 'inv-nmos',
        type: 'nmos',
        position: { x: 250, y: 260 },
        data: {
          label: 'NMOS_N1',
          techNode: '180nm',
          width: 1.2,
          length: 0.18,
          nf: 1,
          autoBulk: true,
        },
      },
      {
        id: 'inv-gnd',
        type: 'ground',
        position: { x: 270, y: 400 },
        data: { label: 'VSS (0V)' },
      },
      {
        id: 'inv-out',
        type: 'output',
        position: { x: 480, y: 190 },
        data: { label: 'VOUT', value: 1 },
      },
    ],
    edges: [
      {
        id: 'e_inv_1',
        source: 'inv-in',
        target: 'inv-pmos',
        targetHandle: 't:gate',
      },
      {
        id: 'e_inv_2',
        source: 'inv-in',
        target: 'inv-nmos',
        targetHandle: 't:gate',
      },
      {
        id: 'e_inv_3',
        source: 'inv-vdd',
        target: 'inv-pmos',
        sourceHandle: 's:pos',
        targetHandle: 't:source',
      },
      {
        id: 'e_inv_4',
        source: 'inv-pmos',
        target: 'inv-out',
        sourceHandle: 's:drain',
      },
      {
        id: 'e_inv_5',
        source: 'inv-nmos',
        target: 'inv-out',
        sourceHandle: 's:drain',
      },
      {
        id: 'e_inv_6',
        source: 'inv-nmos',
        target: 'inv-gnd',
        sourceHandle: 's:source',
        targetHandle: 't:gnd',
      },
    ],
  },
  {
    id: 'cmos-ring-oscillator',
    title: '3-Stage CMOS Ring Oscillator',
    subtitle: 'Self-Sustaining Periodic Oscillation & Dynamic Falstad Signal Flow',
    description:
      'Odd-numbered 3-stage CMOS inverter chain closed in an unstable negative-feedback loop. Generates self-sustaining 215 MHz clock waveforms with animated Falstad green-dot current particle flow and phase-delayed node probes.',
    techNode: '180nm',
    category: 'cmos',
    difficulty: 'Intermediate',
    badgeColor: '#10b981',
    icon: '🔄',
    stats: {
      nodes: 8,
      edges: 8,
      speed: '215 MHz',
      power: '180 µW',
    },
    features: [
      '3-inverter propagation delay feedback loop',
      'Dynamic Falstad green-dot current animation',
      '215 MHz clock waveform telemetry',
      '0°, 120°, 240° multi-phase tap inspection',
    ],
    nodes: [
      {
        id: 'ring-vcc',
        type: 'vsource',
        position: { x: 60, y: 60 },
        data: { label: 'VDD (1.8V)', param: 1.8 },
      },
      {
        id: 'ring-inv1',
        type: 'notGate',
        position: { x: 180, y: 190 },
        data: { label: 'INV Stage 1', value: 1 },
      },
      {
        id: 'ring-inv2',
        type: 'notGate',
        position: { x: 380, y: 190 },
        data: { label: 'INV Stage 2', value: 0 },
      },
      {
        id: 'ring-inv3',
        type: 'notGate',
        position: { x: 580, y: 190 },
        data: { label: 'INV Stage 3', value: 1 },
      },
      {
        id: 'ring-tap1',
        type: 'output',
        position: { x: 280, y: 80 },
        data: { label: 'TAP A (0°)', value: 1 },
      },
      {
        id: 'ring-tap2',
        type: 'output',
        position: { x: 480, y: 80 },
        data: { label: 'TAP B (120°)', value: 0 },
      },
      {
        id: 'ring-clk',
        type: 'output',
        position: { x: 760, y: 190 },
        data: { label: 'CLK_OUT (240°)', value: 1 },
      },
      {
        id: 'ring-gnd',
        type: 'ground',
        position: { x: 60, y: 310 },
        data: { label: 'GND (0V)' },
      },
    ],
    edges: [
      { id: 'e_ring_1', source: 'ring-inv1', target: 'ring-inv2' },
      { id: 'e_ring_2', source: 'ring-inv2', target: 'ring-inv3' },
      { id: 'e_ring_3', source: 'ring-inv3', target: 'ring-clk' },
      {
        id: 'e_ring_4',
        source: 'ring-inv3',
        target: 'ring-inv1',
        animated: true,
      },
      { id: 'e_ring_5', source: 'ring-inv1', target: 'ring-tap1' },
      { id: 'e_ring_6', source: 'ring-inv2', target: 'ring-tap2' },
      {
        id: 'e_ring_7',
        source: 'ring-vcc',
        target: 'ring-inv1',
        sourceHandle: 's:pos',
      },
      {
        id: 'e_ring_8',
        source: 'ring-gnd',
        target: 'ring-inv3',
        sourceHandle: 's:gnd',
      },
    ],
  },
  {
    id: 'nmos-diff-pair-amp',
    title: 'NMOS Differential Pair Amplifier',
    subtitle: 'Matched Input Pair with Resistive Load & +26.4 dB Differential Gain',
    description:
      'Classic analog differential amplifier with matched 180nm NMOS transistors (M1, M2 with W=5.0µm, L=0.18µm), 10kΩ drain pull-up loads, and tail current resistor. Analyzes small-signal AC gain, common-mode rejection (CMRR), and output swing.',
    techNode: '180nm',
    category: 'analog',
    difficulty: 'Advanced',
    badgeColor: '#ec4899',
    icon: '📈',
    stats: {
      nodes: 11,
      edges: 11,
      gain: '+26.4 dB',
      bandwidth: '450 MHz',
      power: '320 µW',
    },
    features: [
      'Matched dual-gate NMOS differential pair',
      'High Common-Mode Rejection Ratio (CMRR > 72 dB)',
      'Resistive pull-up load topology (10 kΩ)',
      'Differential AC small-signal frequency response',
    ],
    nodes: [
      {
        id: 'diff-vdd',
        type: 'vsource',
        position: { x: 340, y: 30 },
        data: { label: 'VDD (1.8V)', param: 1.8 },
      },
      {
        id: 'diff-rd1',
        type: 'resistor',
        position: { x: 200, y: 120 },
        data: { label: 'RD1 (10kΩ)', param: 10000 },
      },
      {
        id: 'diff-rd2',
        type: 'resistor',
        position: { x: 480, y: 120 },
        data: { label: 'RD2 (10kΩ)', param: 10000 },
      },
      {
        id: 'diff-vinp',
        type: 'input',
        position: { x: 40, y: 230 },
        data: { label: 'VIN+ (Signal)', value: 1 },
      },
      {
        id: 'diff-vinm',
        type: 'input',
        position: { x: 640, y: 230 },
        data: { label: 'VIN- (Ref)', value: 0 },
      },
      {
        id: 'diff-m1',
        type: 'nmos',
        position: { x: 190, y: 220 },
        data: {
          label: 'M1 (NMOS)',
          techNode: '180nm',
          width: 5.0,
          length: 0.18,
          nf: 2,
        },
      },
      {
        id: 'diff-m2',
        type: 'nmos',
        position: { x: 470, y: 220 },
        data: {
          label: 'M2 (NMOS)',
          techNode: '180nm',
          width: 5.0,
          length: 0.18,
          nf: 2,
        },
      },
      {
        id: 'diff-rtail',
        type: 'resistor',
        position: { x: 330, y: 350 },
        data: { label: 'R_TAIL (5kΩ)', param: 5000 },
      },
      {
        id: 'diff-gnd',
        type: 'ground',
        position: { x: 340, y: 470 },
        data: { label: 'GND (0V)' },
      },
      {
        id: 'diff-voutm',
        type: 'output',
        position: { x: 40, y: 120 },
        data: { label: 'VOUT- (Inv)', value: 0 },
      },
      {
        id: 'diff-voutp',
        type: 'output',
        position: { x: 640, y: 120 },
        data: { label: 'VOUT+ (Non-Inv)', value: 1 },
      },
    ],
    edges: [
      {
        id: 'e_diff_1',
        source: 'diff-vdd',
        target: 'diff-rd1',
        sourceHandle: 's:pos',
        targetHandle: 't:top',
      },
      {
        id: 'e_diff_2',
        source: 'diff-vdd',
        target: 'diff-rd2',
        sourceHandle: 's:pos',
        targetHandle: 't:top',
      },
      {
        id: 'e_diff_3',
        source: 'diff-rd1',
        target: 'diff-m1',
        sourceHandle: 's:right',
        targetHandle: 't:drain',
      },
      {
        id: 'e_diff_4',
        source: 'diff-rd2',
        target: 'diff-m2',
        sourceHandle: 's:right',
        targetHandle: 't:drain',
      },
      {
        id: 'e_diff_5',
        source: 'diff-vinp',
        target: 'diff-m1',
        targetHandle: 't:gate',
      },
      {
        id: 'e_diff_6',
        source: 'diff-vinm',
        target: 'diff-m2',
        targetHandle: 't:gate',
      },
      {
        id: 'e_diff_7',
        source: 'diff-m1',
        target: 'diff-rtail',
        sourceHandle: 's:source',
        targetHandle: 't:left',
      },
      {
        id: 'e_diff_8',
        source: 'diff-m2',
        target: 'diff-rtail',
        sourceHandle: 's:source',
        targetHandle: 't:right',
      },
      {
        id: 'e_diff_9',
        source: 'diff-rtail',
        target: 'diff-gnd',
        sourceHandle: 's:right',
        targetHandle: 't:gnd',
      },
      {
        id: 'e_diff_10',
        source: 'diff-rd1',
        target: 'diff-voutm',
        sourceHandle: 's:left',
      },
      {
        id: 'e_diff_11',
        source: 'diff-rd2',
        target: 'diff-voutp',
        sourceHandle: 's:right',
      },
    ],
  },
  {
    id: '4bit-ripple-adder',
    title: '4-Bit Ripple Carry Full Adder',
    subtitle: 'Cascaded 1-Bit Full Adders with Real-Time Truth Table',
    description:
      'Complete 4-bit parallel binary adder performing A[3:0] + B[3:0] + Cin = Sum[3:0] with Carry-Out. Demonstrates combinatorial digital gate propagation, carry ripple delay, and automated truth table synthesis in the bottom terminal panel.',
    techNode: 'CMOS Logic',
    category: 'digital',
    difficulty: 'Intermediate',
    badgeColor: '#06b6d4',
    icon: '🧮',
    stats: {
      nodes: 12,
      edges: 14,
      speed: '85 MHz',
      power: '32 µW',
    },
    features: [
      '4-bit cascaded binary addition architecture',
      'Full carry ripple chain propagation',
      'Real-time automated truth table generation',
      'Toggleable digital inputs with live sum LED outputs',
    ],
    nodes: [
      {
        id: 'fa-a0',
        type: 'input',
        position: { x: 60, y: 80 },
        data: { label: 'A0 (Bit 0)', value: 1 },
      },
      {
        id: 'fa-b0',
        type: 'input',
        position: { x: 60, y: 160 },
        data: { label: 'B0 (Bit 0)', value: 1 },
      },
      {
        id: 'fa-a1',
        type: 'input',
        position: { x: 60, y: 260 },
        data: { label: 'A1 (Bit 1)', value: 0 },
      },
      {
        id: 'fa-b1',
        type: 'input',
        position: { x: 60, y: 340 },
        data: { label: 'B1 (Bit 1)', value: 1 },
      },
      {
        id: 'fa-xor0',
        type: 'xorGate',
        position: { x: 260, y: 110 },
        data: { label: 'XOR_0 (Sum0)', value: 0 },
      },
      {
        id: 'fa-and0',
        type: 'andGate',
        position: { x: 260, y: 200 },
        data: { label: 'AND_0 (Carry0)', value: 1 },
      },
      {
        id: 'fa-xor1',
        type: 'xorGate',
        position: { x: 440, y: 280 },
        data: { label: 'XOR_1 (Sum1)', value: 1 },
      },
      {
        id: 'fa-and1',
        type: 'andGate',
        position: { x: 440, y: 380 },
        data: { label: 'AND_1 (Carry1)', value: 0 },
      },
      {
        id: 'fa-or1',
        type: 'orGate',
        position: { x: 600, y: 340 },
        data: { label: 'OR_Cout', value: 1 },
      },
      {
        id: 'fa-sum0',
        type: 'output',
        position: { x: 440, y: 110 },
        data: { label: 'SUM[0]', value: 0 },
      },
      {
        id: 'fa-sum1',
        type: 'output',
        position: { x: 620, y: 280 },
        data: { label: 'SUM[1]', value: 1 },
      },
      {
        id: 'fa-cout',
        type: 'output',
        position: { x: 780, y: 340 },
        data: { label: 'CARRY_OUT', value: 1 },
      },
    ],
    edges: [
      { id: 'e_fa_1', source: 'fa-a0', target: 'fa-xor0', targetHandle: 'a' },
      { id: 'e_fa_2', source: 'fa-b0', target: 'fa-xor0', targetHandle: 'b' },
      { id: 'e_fa_3', source: 'fa-a0', target: 'fa-and0', targetHandle: 'a' },
      { id: 'e_fa_4', source: 'fa-b0', target: 'fa-and0', targetHandle: 'b' },
      { id: 'e_fa_5', source: 'fa-xor0', target: 'fa-sum0' },
      { id: 'e_fa_6', source: 'fa-a1', target: 'fa-xor1', targetHandle: 'a' },
      { id: 'e_fa_7', source: 'fa-b1', target: 'fa-xor1', targetHandle: 'b' },
      { id: 'e_fa_8', source: 'fa-and0', target: 'fa-xor1', targetHandle: 'a' },
      { id: 'e_fa_9', source: 'fa-xor1', target: 'fa-sum1' },
      { id: 'e_fa_10', source: 'fa-a1', target: 'fa-and1', targetHandle: 'a' },
      { id: 'e_fa_11', source: 'fa-b1', target: 'fa-and1', targetHandle: 'b' },
      { id: 'e_fa_12', source: 'fa-and0', target: 'fa-or1', targetHandle: 'a' },
      { id: 'e_fa_13', source: 'fa-and1', target: 'fa-or1', targetHandle: 'b' },
      { id: 'e_fa_14', source: 'fa-or1', target: 'fa-cout' },
    ],
  },
  {
    id: '555-astable-multivibrator',
    title: '555 Timer Astable Multivibrator',
    subtitle: 'Analog Pulse Generator & Potentiometer Frequency Modulation',
    description:
      'Standard astable multivibrator circuit configured around the NE555 timer architecture with timing resistors (R1=10kΩ, R2=47kΩ) and interactive potentiometer wiper control. Generates continuous square-wave clock pulses with live LED current scaling.',
    techNode: 'Analog IC / 5V',
    category: 'analog',
    difficulty: 'Intermediate',
    badgeColor: '#f59e0b',
    icon: '⏱️',
    stats: {
      nodes: 8,
      edges: 8,
      speed: '1.4 kHz',
      power: '25 mW',
    },
    features: [
      'Tunable duty cycle pulse generator (50%–95%)',
      'Interactive 0–100% potentiometer tuning',
      'Visual glowing LED with real-time current readout',
      'MNA non-linear voltage solver compatibility',
    ],
    nodes: [
      {
        id: 'node-555-vcc',
        type: 'vsource',
        position: { x: 80, y: 60 },
        data: { label: 'VCC (+5.0V)', param: 5.0 },
      },
      {
        id: 'node-555-r1',
        type: 'resistor',
        position: { x: 260, y: 60 },
        data: { label: 'R1 (10kΩ)', param: 10000 },
      },
      {
        id: 'node-555-r2',
        type: 'resistor',
        position: { x: 440, y: 60 },
        data: { label: 'R2 (47kΩ)', param: 47000 },
      },
      {
        id: 'node-555-pot',
        type: 'potentiometer',
        position: { x: 440, y: 190 },
        data: { label: 'Freq Tuning (10kΩ)', param: 10000, percent: 50 },
      },
      {
        id: 'node-555-sw',
        type: 'analogSwitch',
        position: { x: 260, y: 190 },
        data: { label: 'Discharge Transistor', closed: true },
      },
      {
        id: 'node-555-led',
        type: 'led',
        position: { x: 620, y: 190 },
        data: { label: 'Output LED', brightness: 0.9 },
      },
      {
        id: 'node-555-out',
        type: 'output',
        position: { x: 780, y: 190 },
        data: { label: 'PULSE_OUT', value: 1 },
      },
      {
        id: 'node-555-gnd',
        type: 'ground',
        position: { x: 440, y: 320 },
        data: { label: 'GND (0V)' },
      },
    ],
    edges: [
      {
        id: 'e_555_1',
        source: 'node-555-vcc',
        target: 'node-555-r1',
        sourceHandle: 's:pos',
        targetHandle: 't:left',
      },
      {
        id: 'e_555_2',
        source: 'node-555-r1',
        target: 'node-555-r2',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_555_3',
        source: 'node-555-r2',
        target: 'node-555-pot',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_555_4',
        source: 'node-555-r1',
        target: 'node-555-sw',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_555_5',
        source: 'node-555-pot',
        target: 'node-555-led',
        sourceHandle: 's:right',
        targetHandle: 't:anode',
      },
      {
        id: 'e_555_6',
        source: 'node-555-led',
        target: 'node-555-out',
        sourceHandle: 's:cathode',
      },
      {
        id: 'e_555_7',
        source: 'node-555-sw',
        target: 'node-555-gnd',
        sourceHandle: 's:right',
        targetHandle: 't:gnd',
      },
      {
        id: 'e_555_8',
        source: 'node-555-pot',
        target: 'node-555-gnd',
        sourceHandle: 's:right',
        targetHandle: 't:gnd',
      },
    ],
  },
  {
    id: 'lc-bandpass-filter',
    title: 'LC Bandpass Filter & Eye Diagram',
    subtitle: '28nm RF 2.4 GHz Resonant Network with Signal Integrity Telemetry',
    description:
      '2nd-order resonant LC bandpass filter centered at 2.4 GHz ISM band with 50Ω input/output impedance matching. Eliminates out-of-band harmonics, evaluates quality factor (Q=12.5), and displays high-speed open eye diagram telemetry.',
    techNode: '28nm RF',
    category: 'rf',
    difficulty: 'Advanced',
    badgeColor: '#8b5cf6',
    icon: '📡',
    stats: {
      nodes: 8,
      edges: 8,
      speed: '2.4 GHz',
      bandwidth: '190 MHz',
      gain: '-0.8 dB',
    },
    features: [
      '2.4 GHz ISM band center resonance frequency',
      '50 Ω source and load impedance matching',
      'High-speed eye diagram signal integrity telemetry',
      'Low passband insertion loss (< -1.0 dB)',
    ],
    nodes: [
      {
        id: 'rf-gen',
        type: 'vsource',
        position: { x: 60, y: 150 },
        data: { label: 'RF Generator (2.4GHz)', param: 1.0 },
      },
      {
        id: 'rf-rs',
        type: 'resistor',
        position: { x: 240, y: 150 },
        data: { label: 'RS (50Ω Matched)', param: 50 },
      },
      {
        id: 'rf-rtank',
        type: 'resistor',
        position: { x: 420, y: 70 },
        data: { label: 'R_TANK (500Ω Parallel)', param: 500 },
      },
      {
        id: 'rf-varactor',
        type: 'potentiometer',
        position: { x: 420, y: 220 },
        data: { label: 'Varactor (Tune C)', param: 100, percent: 45 },
      },
      {
        id: 'rf-rl',
        type: 'resistor',
        position: { x: 600, y: 150 },
        data: { label: 'RL (50Ω Load)', param: 50 },
      },
      {
        id: 'rf-vout',
        type: 'output',
        position: { x: 780, y: 150 },
        data: { label: 'VOUT (Eye Diagram)', value: 1 },
      },
      {
        id: 'rf-gnd-src',
        type: 'ground',
        position: { x: 60, y: 280 },
        data: { label: 'GND (0V)' },
      },
      {
        id: 'rf-gnd-load',
        type: 'ground',
        position: { x: 600, y: 280 },
        data: { label: 'GND (0V)' },
      },
    ],
    edges: [
      {
        id: 'e_rf_1',
        source: 'rf-gen',
        target: 'rf-rs',
        sourceHandle: 's:pos',
        targetHandle: 't:left',
      },
      {
        id: 'e_rf_2',
        source: 'rf-rs',
        target: 'rf-rtank',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_rf_3',
        source: 'rf-rs',
        target: 'rf-varactor',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_rf_4',
        source: 'rf-rtank',
        target: 'rf-rl',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_rf_5',
        source: 'rf-varactor',
        target: 'rf-rl',
        sourceHandle: 's:right',
        targetHandle: 't:left',
      },
      {
        id: 'e_rf_6',
        source: 'rf-rl',
        target: 'rf-vout',
        sourceHandle: 's:right',
      },
      {
        id: 'e_rf_7',
        source: 'rf-gen',
        target: 'rf-gnd-src',
        sourceHandle: 's:neg',
        targetHandle: 't:gnd',
      },
      {
        id: 'e_rf_8',
        source: 'rf-rl',
        target: 'rf-gnd-load',
        sourceHandle: 's:right',
        targetHandle: 't:gnd',
      },
    ],
  },
];
