/**
 * @file gerberExport.ts
 * @description Generates standard RS-274X PCB Gerber files (.gbr) from DigiSim
 * schematic node placement and trace routes. Provides aperture definitions,
 * pad flashing for ICs/pins, copper trace line interpolation, and direct file download.
 */

import type { DigiEdge, DigiNode } from '../types';

export interface GerberExportOptions {
  layerName?: string;
  unit?: 'MM' | 'IN';
  boardPadding?: number;
  traceWidthMm?: number;
  padDiameterMm?: number;
}

/**
 * Format a number to standard Gerber 4.4 coordinate format (fixed 4 integer, 4 decimals).
 * Coordinates in mm are scaled to 10^-4 mm integer string without decimal point.
 */
function formatGerberCoord(valMm: number): string {
  const scaled = Math.round(valMm * 10000);
  return String(scaled);
}

/**
 * Generate RS-274X Gerber string representation of the circuit PCB top copper layer.
 *
 * @param nodes - Canvas nodes
 * @param edges - Canvas edges (wires / traces)
 * @param options - Layer name and scale options
 * @returns RS-274X formatted ASCII Gerber stream
 */
export function generateGerberRS274X(
  nodes: DigiNode[],
  edges: DigiEdge[],
  options: GerberExportOptions = {}
): string {
  const layerName = options.layerName ?? 'Top_Copper_GTL';
  const traceWidth = options.traceWidthMm ?? 0.35; // 0.35mm standard trace
  const padDiameter = options.padDiameterMm ?? 1.6; // 1.6mm pad

  // Find canvas bounding box to normalize to PCB origin (0,0) with margin
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  if (nodes.length === 0) {
    minX = 0;
    minY = 0;
    maxX = 100;
    maxY = 100;
  } else {
    for (const node of nodes) {
      minX = Math.min(minX, node.position.x);
      minY = Math.min(minY, node.position.y);
      maxX = Math.max(maxX, node.position.x + 120);
      maxY = Math.max(maxY, node.position.y + 80);
    }
  }

  // Conversion: 10 pixels = ~2.54mm (0.1 inch standard grid pitch)
  const scale = 0.254; // mm per canvas pixel
  const padding = options.boardPadding ?? 10; // 10mm board edge margin

  const toX = (px: number): number => (px - minX) * scale + padding;
  const toY = (py: number): number => (py - minY) * scale + padding;

  const lines: string[] = [];

  // 1. Gerber Header & Standard Modes
  lines.push('G04*');
  lines.push(`G04 Layer: ${layerName}*`);
  lines.push('G04 Generated by DigiSim AI EDA Platform*');
  lines.push('G04 Format: RS-274X, Metric (mm), 4.4 Absolute*');
  lines.push('G04*');
  lines.push('%FSLAX44Y44*%'); // Format specification
  lines.push('%MOMM*%'); // Millimeters
  lines.push(`%LN${layerName}*%`); // Layer Name
  lines.push('%LPD*%'); // Dark polarity
  lines.push('%IPPOS*%'); // Positive image

  // 2. Aperture Table Definition
  // D10: Circular Aperture for Traces
  lines.push(`%ADD10C,${traceWidth.toFixed(4)}*%`);
  // D11: Circular Aperture for Component Pads
  lines.push(`%ADD11C,${padDiameter.toFixed(4)}*%`);
  // D12: Rectangular Aperture for SMD Pads / IC Pins
  lines.push('%ADD12R,1.8000X1.0000*%');
  // D13: Board Outline Trace Aperture
  lines.push('%ADD13C,0.2000*%');

  // 3. Board Outline (D13)
  const bWidth = (maxX - minX) * scale + padding * 2;
  const bHeight = (maxY - minY) * scale + padding * 2;
  lines.push('G04 Board Outline*');
  lines.push('D13*');
  lines.push(`X${formatGerberCoord(0)}Y${formatGerberCoord(0)}D02*`);
  lines.push(`X${formatGerberCoord(bWidth)}Y${formatGerberCoord(0)}D01*`);
  lines.push(`X${formatGerberCoord(bWidth)}Y${formatGerberCoord(bHeight)}D01*`);
  lines.push(`X${formatGerberCoord(0)}Y${formatGerberCoord(bHeight)}D01*`);
  lines.push(`X${formatGerberCoord(0)}Y${formatGerberCoord(0)}D01*`);

  // 4. Component Pads (D11 and D12)
  lines.push('G04 Component Pads and Terminals*');
  lines.push('D11*'); // Flash circular pads
  const nodeMap = new Map<string, DigiNode>();
  for (const node of nodes) {
    nodeMap.set(node.id, node);
    const nx = toX(node.position.x + 30);
    const ny = toY(node.position.y + 20);
    lines.push(`X${formatGerberCoord(nx)}Y${formatGerberCoord(ny)}D03*`);

    // Additional pad for 2-terminal/multi-terminal parts
    const nx2 = toX(node.position.x + 80);
    const ny2 = toY(node.position.y + 20);
    lines.push(`X${formatGerberCoord(nx2)}Y${formatGerberCoord(ny2)}D03*`);
  }

  // 5. Copper Traces (D10)
  lines.push('G04 Copper Signal Traces*');
  lines.push('D10*'); // Draw with 0.35mm circular aperture
  for (const edge of edges) {
    const srcNode = nodeMap.get(edge.source);
    const tgtNode = nodeMap.get(edge.target);
    if (!srcNode || !tgtNode) continue;

    const startX = toX(srcNode.position.x + 80);
    const startY = toY(srcNode.position.y + 20);
    const endX = toX(tgtNode.position.x + 30);
    const endY = toY(tgtNode.position.y + 20);
    const midX = (startX + endX) / 2;

    // Route orthogonal/45-degree trace: start -> (midX, startY) -> (midX, endY) -> end
    lines.push(`X${formatGerberCoord(startX)}Y${formatGerberCoord(startY)}D02*`);
    lines.push(`X${formatGerberCoord(midX)}Y${formatGerberCoord(startY)}D01*`);
    lines.push(`X${formatGerberCoord(midX)}Y${formatGerberCoord(endY)}D01*`);
    lines.push(`X${formatGerberCoord(endX)}Y${formatGerberCoord(endY)}D01*`);
  }

  // 6. Gerber End of File
  lines.push('M02*');

  return lines.join('\n');
}

/**
 * Trigger browser file download of standard RS-274X Gerber file (.gbr).
 *
 * @param nodes - Schematic nodes
 * @param edges - Schematic edges
 * @param filename - Base name of the file without extension
 */
export function downloadGerberFile(
  nodes: DigiNode[],
  edges: DigiEdge[],
  filename = 'digisim_top_copper'
): void {
  const gbrContent = generateGerberRS274X(nodes, edges, { layerName: filename });
  const blob = new Blob([gbrContent], { type: 'application/octet-stream;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename.endsWith('.gbr') ? filename : `${filename}.gbr`;
  anchor.click();
  URL.revokeObjectURL(url);
}
